# Generated by Django 4.2.7 on 2024-08-03 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedalTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rank', models.CharField(max_length=256)),
                ('Country', models.CharField(choices=[], max_length=256)),
                ('Flag', models.CharField(max_length=256)),
                ('Gold', models.CharField(max_length=256)),
                ('Silver', models.CharField(max_length=256)),
                ('Bronze', models.CharField(max_length=256)),
                ('Total', models.CharField(max_length=256)),
            ],
        ),
    ]
