# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: nosa2k
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: olympicmedalproject
	
service: olympicmedalproject
 
provider:
  name: aws
  runtime: python3.11
  stage: dev
  region: us-east-2
  profile: default
 
 
 
plugins:
  - serverless-wsgi
  - serverless-python-requirements
 
functions:
  api:
    handler: wsgi_handler.handler
    events:
      - http: ANY /
      - http: ANY /{proxy+}

 
custom:
  wsgi:
    app: olympic_project.wsgi.application
    packRequirements: false
  pythonRequirements:
    dockerizePip: true